// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/entities/proto/env.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvVariables struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DISCORD_TOKEN        string                 `protobuf:"bytes,1,opt,name=DISCORD_TOKEN,json=DISCORDTOKEN,proto3" json:"DISCORD_TOKEN,omitempty"`
	REMOVE_BG_API_KEY    string                 `protobuf:"bytes,2,opt,name=REMOVE_BG_API_KEY,json=REMOVEBGAPIKEY,proto3" json:"REMOVE_BG_API_KEY,omitempty"`
	REMOVE_BG_API_URL    string                 `protobuf:"bytes,3,opt,name=REMOVE_BG_API_URL,json=REMOVEBGAPIURL,proto3" json:"REMOVE_BG_API_URL,omitempty"`
	JOKES_API_URL        string                 `protobuf:"bytes,4,opt,name=JOKES_API_URL,json=JOKESAPIURL,proto3" json:"JOKES_API_URL,omitempty"`
	ANIME_QUOTE_API_URL  string                 `protobuf:"bytes,5,opt,name=ANIME_QUOTE_API_URL,json=ANIMEQUOTEAPIURL,proto3" json:"ANIME_QUOTE_API_URL,omitempty"`
	DISTRO_INFO_API_URL  string                 `protobuf:"bytes,6,opt,name=DISTRO_INFO_API_URL,json=DISTROINFOAPIURL,proto3" json:"DISTRO_INFO_API_URL,omitempty"`
	DOA_API_URL          string                 `protobuf:"bytes,7,opt,name=DOA_API_URL,json=DOAAPIURL,proto3" json:"DOA_API_URL,omitempty"`
	QURAN_API_URL        string                 `protobuf:"bytes,8,opt,name=QURAN_API_URL,json=QURANAPIURL,proto3" json:"QURAN_API_URL,omitempty"`
	IMAGE_API_URL        string                 `protobuf:"bytes,9,opt,name=IMAGE_API_URL,json=IMAGEAPIURL,proto3" json:"IMAGE_API_URL,omitempty"`
	GEMINI_API_KEY       string                 `protobuf:"bytes,10,opt,name=GEMINI_API_KEY,json=GEMINIAPIKEY,proto3" json:"GEMINI_API_KEY,omitempty"`
	ASMAUL_HUSNA_API_URL string                 `protobuf:"bytes,11,opt,name=ASMAUL_HUSNA_API_URL,json=ASMAULHUSNAAPIURL,proto3" json:"ASMAUL_HUSNA_API_URL,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EnvVariables) Reset() {
	*x = EnvVariables{}
	mi := &file_pkg_entities_proto_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVariables) ProtoMessage() {}

func (x *EnvVariables) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_proto_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVariables.ProtoReflect.Descriptor instead.
func (*EnvVariables) Descriptor() ([]byte, []int) {
	return file_pkg_entities_proto_env_proto_rawDescGZIP(), []int{0}
}

func (x *EnvVariables) GetDISCORD_TOKEN() string {
	if x != nil {
		return x.DISCORD_TOKEN
	}
	return ""
}

func (x *EnvVariables) GetREMOVE_BG_API_KEY() string {
	if x != nil {
		return x.REMOVE_BG_API_KEY
	}
	return ""
}

func (x *EnvVariables) GetREMOVE_BG_API_URL() string {
	if x != nil {
		return x.REMOVE_BG_API_URL
	}
	return ""
}

func (x *EnvVariables) GetJOKES_API_URL() string {
	if x != nil {
		return x.JOKES_API_URL
	}
	return ""
}

func (x *EnvVariables) GetANIME_QUOTE_API_URL() string {
	if x != nil {
		return x.ANIME_QUOTE_API_URL
	}
	return ""
}

func (x *EnvVariables) GetDISTRO_INFO_API_URL() string {
	if x != nil {
		return x.DISTRO_INFO_API_URL
	}
	return ""
}

func (x *EnvVariables) GetDOA_API_URL() string {
	if x != nil {
		return x.DOA_API_URL
	}
	return ""
}

func (x *EnvVariables) GetQURAN_API_URL() string {
	if x != nil {
		return x.QURAN_API_URL
	}
	return ""
}

func (x *EnvVariables) GetIMAGE_API_URL() string {
	if x != nil {
		return x.IMAGE_API_URL
	}
	return ""
}

func (x *EnvVariables) GetGEMINI_API_KEY() string {
	if x != nil {
		return x.GEMINI_API_KEY
	}
	return ""
}

func (x *EnvVariables) GetASMAUL_HUSNA_API_URL() string {
	if x != nil {
		return x.ASMAUL_HUSNA_API_URL
	}
	return ""
}

var File_pkg_entities_proto_env_proto protoreflect.FileDescriptor

const file_pkg_entities_proto_env_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/entities/proto/env.proto\x12\bentities\"\xca\x03\n" +
	"\fEnvVariables\x12#\n" +
	"\rDISCORD_TOKEN\x18\x01 \x01(\tR\fDISCORDTOKEN\x12)\n" +
	"\x11REMOVE_BG_API_KEY\x18\x02 \x01(\tR\x0eREMOVEBGAPIKEY\x12)\n" +
	"\x11REMOVE_BG_API_URL\x18\x03 \x01(\tR\x0eREMOVEBGAPIURL\x12\"\n" +
	"\rJOKES_API_URL\x18\x04 \x01(\tR\vJOKESAPIURL\x12-\n" +
	"\x13ANIME_QUOTE_API_URL\x18\x05 \x01(\tR\x10ANIMEQUOTEAPIURL\x12-\n" +
	"\x13DISTRO_INFO_API_URL\x18\x06 \x01(\tR\x10DISTROINFOAPIURL\x12\x1e\n" +
	"\vDOA_API_URL\x18\a \x01(\tR\tDOAAPIURL\x12\"\n" +
	"\rQURAN_API_URL\x18\b \x01(\tR\vQURANAPIURL\x12\"\n" +
	"\rIMAGE_API_URL\x18\t \x01(\tR\vIMAGEAPIURL\x12$\n" +
	"\x0eGEMINI_API_KEY\x18\n" +
	" \x01(\tR\fGEMINIAPIKEY\x12/\n" +
	"\x14ASMAUL_HUSNA_API_URL\x18\v \x01(\tR\x11ASMAULHUSNAAPIURLB%Z#katou-megumi/pkg/entities/generatedb\x06proto3"

var (
	file_pkg_entities_proto_env_proto_rawDescOnce sync.Once
	file_pkg_entities_proto_env_proto_rawDescData []byte
)

func file_pkg_entities_proto_env_proto_rawDescGZIP() []byte {
	file_pkg_entities_proto_env_proto_rawDescOnce.Do(func() {
		file_pkg_entities_proto_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_entities_proto_env_proto_rawDesc), len(file_pkg_entities_proto_env_proto_rawDesc)))
	})
	return file_pkg_entities_proto_env_proto_rawDescData
}

var file_pkg_entities_proto_env_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_entities_proto_env_proto_goTypes = []any{
	(*EnvVariables)(nil), // 0: entities.EnvVariables
}
var file_pkg_entities_proto_env_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_entities_proto_env_proto_init() }
func file_pkg_entities_proto_env_proto_init() {
	if File_pkg_entities_proto_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_entities_proto_env_proto_rawDesc), len(file_pkg_entities_proto_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_entities_proto_env_proto_goTypes,
		DependencyIndexes: file_pkg_entities_proto_env_proto_depIdxs,
		MessageInfos:      file_pkg_entities_proto_env_proto_msgTypes,
	}.Build()
	File_pkg_entities_proto_env_proto = out.File
	file_pkg_entities_proto_env_proto_goTypes = nil
	file_pkg_entities_proto_env_proto_depIdxs = nil
}
